name: PerchTrackers
version: 1.1.0
main: me.perch.Trackers
api-version: 1.21.11
authors: [KayaLambrex, Dypel]
depend:
  - Votifier
commands:
  trackers:
    description: Admin command to manage trackers
    usage: /trackers <give|remove>
    permission: perchtrackers.admin
permissions:
  perchtrackers.admin:
    description: Allows full access to tracker commands
    default: op